### ISSUE TITLE
Old news article are 404

### ISSUE THREAD

**Issue by romangg** [manjaro/website#40]
I assume this is due to #25 articles on previous pages are not generated as a link to them is only created on client side.

**Comment by nurRiyad** [comment]
Hopefully I will resolve this issue in the weekend

**Comment by nurRiyad** [comment]
Hi @romangg  After researching  what I found is, In Next3 when we are prerendering we can not generate all possible routes without linking them. I tried query params with link. But What I found is query params will also not work. 

**Reference** 

> Query strings are not supported when prerendering because they can't be saved to disk and served with a static file server - e.g. index?page=1.html.

>This behavior was also the same in https://github.com/nuxt/nuxt.js/issues/7627. I'm unsure how practical it is to implement it so that there can be multiple payloads per page based on the query.
Is there any reason why you would not use page params (via the router) instead? Like /page/3 instead of ?page=3

https://github.com/nuxt/nuxt/issues/15096#issuecomment-1397371996
https://github.com/nuxt/nuxt/issues/22197
https://github.com/nuxt/nuxt/issues/7627

**What they suggest**
>  /page/3 instead of ?page=3

So the one option I have is to use dynamic route params. I will update the pagination component to use dynamic route params. And hopefully I will some the issue.

**Comment by nurRiyad** [comment]
Fixed #43

**Comment by romangg** [comment]
> In Next3 when we are prerendering we can not generate all possible routes without linking them.

It's similar to the issue I had with NuxtImg not creating images for the static build when it's behind some client-side conditional rendering logic, see aecc8099fbae39f2f8a47912e23426a60a5ee2b7.

Something to be aware of when building static sites with Nuxt.

**Comment by romangg** [comment]
Fixed by #43.
